"""
debug.py -- Diagnostic and support bundle framework.

Creates redacted, deterministic support bundles. Secrets are never copied.
"""
from __future__ import annotations
import hashlib, json, os, tarfile, tempfile, shutil
from datetime import datetime, timezone
from pathlib import Path

from .evidence_signing import (
    EvidenceSigner, EvidenceSigningError, configured_trusted_fingerprints,
    signing_required, verify_signed_archive,
)

SECRET_KEYS = {
    "password","secret","token","community","private_key","private",
    "master","oauth_secret","client_secret","api_token"
}

def redact(obj):
    if isinstance(obj, dict):
        out={}
        for k,v in obj.items():
            if any(x in str(k).lower() for x in SECRET_KEYS):
                out[k]="<redacted>"
            else:
                out[k]=redact(v)
        return out
    if isinstance(obj, list):
        return [redact(x) for x in obj]
    return obj

def sha256_file(path):
    h=hashlib.sha256()
    with open(path,"rb") as f:
        for chunk in iter(lambda:f.read(1024*1024), b""):
            h.update(chunk)
    return h.hexdigest()

class DebugBundle:
    def __init__(self, manager):
        self.manager=manager
        self.root = Path(getattr(manager.paths, "home", ".")) / "debug-bundles"
        self.root.mkdir(parents=True, exist_ok=True)

    def list_bundles(self):
        result=[]
        for p in sorted(self.root.glob("*.tar.gz"), reverse=True):
            result.append({"name": p.name, "size": p.stat().st_size})
        return result

    def get_bundle(self, name):
        """Return a managed bundle Path or None; never resolve arbitrary paths."""
        raw = str(name or "")
        safe = Path(raw).name
        if not safe or safe != raw or not safe.endswith(".tar.gz"):
            return None
        target = self.root / safe
        return target if target.is_file() else None

    def cleanup(self, keep=10):
        bundles=sorted(self.root.glob("*.tar.gz"), reverse=True)
        removed=[]
        for p in bundles[keep:]:
            p.unlink(missing_ok=True)
            removed.append(p.name)
        return removed

    def collect(self, output=None, require_signature=False):
        stamp=datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        base=Path(tempfile.mkdtemp(prefix="netconfig-support-"))
        for d in ("system","config","logs","database","security"):
            (base/d).mkdir(parents=True, exist_ok=True)

        self._json(base/"system"/"runtime.json", {
            "timestamp": stamp,
            "version": getattr(self.manager, "VERSION", "unknown"),
            "python": os.sys.version,
        })
        self._json(base/"system"/"health.json", {"status":"unknown",
            "note":"generated by diagnostic collector"})
        self._json(base/"config"/"sanitized-config.json",
                   redact(getattr(self.manager, "settings", {})))
        self._json(base/"security"/"redaction-report.json",
                   {"performed": True, "secret_patterns_checked": sorted(SECRET_KEYS)})
        self._json(base/"database"/"metadata.json",
                   {"path": str(getattr(self.manager.paths,"db_file",""))})
        sessions = self.manager.protocol_traces.list(limit=20)
        self._json(base/"logs"/"protocol-traces.json", [
            {"session": row, "events": self.manager.protocol_traces.events(row["id"], 200)}
            for row in sessions
        ])

        out=Path(output) if output else self.root/f"netconfig-support-{stamp}.tar.gz"
        try:
            self._finalize_manifest(base, stamp, require_signature=require_signature)
            with tarfile.open(out,"w:gz") as tar:
                tar.add(base, arcname=base.name)
            return out
        finally:
            shutil.rmtree(base, ignore_errors=True)

    def device_capture(self, device_name, output=None, require_signature=False):
        """Create a redacted single-device diagnostic capture."""
        stamp=datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        base=Path(tempfile.mkdtemp(prefix="netconfig-device-debug-"))
        (base / "device").mkdir(parents=True, exist_ok=True)
        dev=self.manager.inv.get(device_name)
        if not dev:
            raise ValueError(f"unknown device: {device_name}")
        self._json(base/"device"/"inventory.json", dev)
        self._json(base/"device"/"topology.json", [n for n in self.manager.topology() if n.get("local_device")==device_name or n.get("device")==device_name])
        self._json(base/"device"/"drift.json", self.manager.check_drift(device_name))
        self._json(base/"device"/"collection.json", {"device": device_name, "captured": stamp})
        sessions = self.manager.protocol_traces.list(device=device_name, limit=20)
        self._json(base/"device"/"protocol-traces.json", [
            {"session": row, "events": self.manager.protocol_traces.events(row["id"], 200)}
            for row in sessions
        ])
        self._json(base/"security"/"redaction-report.json", {"performed": True, "secret_patterns_checked": sorted(SECRET_KEYS)})
        return self._archive(base, output, "device", require_signature=require_signature)

    def _archive(self, base, output, prefix, require_signature=False):
        out=Path(output) if output else self.root/f"netconfig-{prefix}-support-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}.tar.gz"
        try:
            self._finalize_manifest(base, datetime.now(timezone.utc).isoformat(),
                                    require_signature=require_signature)
            with tarfile.open(out,"w:gz") as tar:
                tar.add(base, arcname=base.name)
            return out
        finally:
            shutil.rmtree(base, ignore_errors=True)

    def _finalize_manifest(self, base, created, require_signature=False):
        manifest=[]
        for p in sorted(base.rglob("*")):
            if p.is_file() and p.name not in {"manifest.json", "manifest.sha256",
                                               "manifest.signature.json", "manifest.public.pem"}:
                manifest.append({"path":str(p.relative_to(base)),
                                 "sha256":sha256_file(p),"size":p.stat().st_size})
        signer = EvidenceSigner()
        require_signing = bool(require_signature or signing_required(self.manager.settings))
        identity = None
        if signer.available:
            identity = signer.identity()
        elif require_signing:
            raise EvidenceSigningError("evidence signing is required but no signing key is configured")
        self._json(base/"manifest.json", {
            "schema": "netconfig-diagnostic-manifest-v2",
            "created": created,
            "files": manifest,
            "signing": ({"status": "SIGNED", "algorithm": identity["algorithm"],
                         "key_fingerprint": identity["key_fingerprint"]}
                        if identity else {"status": "UNSIGNED"}),
        })
        digest=sha256_file(base/"manifest.json")
        (base/"manifest.sha256").write_text(f"{digest}  manifest.json\n", encoding="ascii")
        if identity:
            signer.sign_manifest(base/"manifest.json", base)

    def verify_bundle(self, name, trusted_fingerprints=None):
        target = self.get_bundle(name)
        if target is None:
            raise ValueError("diagnostic bundle not found")
        trusted = configured_trusted_fingerprints(
            settings=self.manager.settings, extra=trusted_fingerprints)
        return verify_signed_archive(target, trusted)

    def _json(self,path,data):
        path.write_text(json.dumps(redact(data), indent=2, sort_keys=True),
                        encoding="utf-8")
